[mission]
title = "战役"
type = "战役类型"

[multiplayer]
host = "创建房间"
replay = "观看回放"
joinLastGame = "加入上一次游戏"
blacklist = "黑名单"
playerLimit = "玩家限制"
enableMods = "启动模组"
reset = "重置"
hostByProtocol= "以{0}创建房间"
joinServer = "加入服务器"
userName = "用户名"
useAsDefaultList = "用作默认房间列表"
battleroom = "战役室"
transferMod = "传输模组"
addToBlackList = "添加进黑名单"
join = "加入"
password = "密码"
hostPublic = "创建公开"
hostPrivate = "创建私有"
port = "端口"
roomInfo = """
房主: {0}
地图: {1}
玩家: {2}/{3}
版本: {4}
模组: {5}
"""
admitting = """
为了使RWPP能变得更好，我们希望您在开房时向进入的玩家发送一条消息用以推广RWPP
您是否同意？(该对话框第一次显示后将不再显示，稍后可在 设置 - Show Welcome Message中更改)
"""

[multiplayer.filter]
gameMapNameFilter = "地图名称"
creatorNameFilter = "创建者"
playerLimitRange = "玩家限制范围"
blacklist = "黑名单"
reset = "重置"

[multiplayer.room]
selectMap = "选择地图"
option = "选项"
start = "开始"
changeSite = "更换位置"
addAI = "添加AI"
kick = "踢出"
apply = "应用"
sendMessage = "发送消息"
noNukes = "禁用核弹"
sharedControl = "共享控制"
allowSpectators = "允许观战"
teamLock = "队伍锁定"
playerConfig = "玩家配置"
startingUnit = "初始单位"
startingCredits = "初始资金"
maxPlayer = "最大玩家数"
incomeMultiplier = "资金倍率"
teamUnitCapHostedGame = "团队最大单位数量"
banUnits = "禁用单位"
mapView = "地图视图"
mapType = "地图类型"
spawnPointTip = "出生点控制着玩家在地图上的初始位置。大多数地图使用偶数出生点。"
teamTip = "具有相同队伍的玩家将会团结在一起。"
setTeam = "设置队伍"
gameSpeed = "游戏速度 (实验性)"

[mod]
update = "刷新"
reload = "重载"
disableAll = "禁用全部"
apply = "应用"
cancel = "取消"
delete = "删除"
enabled = "已启用"
disabled = "已禁用"
inputFile = "导入文件"
loadInfo = "请导入.rwmod文件"
removeInfo = "删除模组失败，请禁用后并重启重试"

[browser]
user = "用户"
username = "手机/邮箱"
password = "密码"
login = "登录"
resourceBrowser = "资源浏览器"
resourceType = "资源类型"
loadMore = "加载更多"
search = "搜索"

[menu]
mission = "战役"
sandbox = "沙盒编辑器"
multiplayer = "多人游戏"
mods = "模组"
extension = "扩展"
settings = "设置"
exit = "退出"
replay = "观看回放"

[common]
difficulty = "难度"
spawnPoint = "出生点"
team = "队伍"
fog = "迷雾"
mod = "模组"
map = "地图"
filter = "过滤器"

[settings]
setExternalFolder = "设置外部文件权限"
manageAllFiles = "设置管理所有文件"
client = "客户端"
theme = "主题"
autoCheckUpdate = "自动检测更新"
checkUpdate = "检测更新"
newVersion = "检测到新版本: {0}, 可以前往以下站点下载"
goToDownload = "前往 {0} 下载"
prereleaseNote = "注意: 该版本为预览版，可以前往爱发电下载抢先体验"
ignoreVersion = "忽略此版本"
teamUnitCapHostedGame = "团队最大单位数量"
teamUnitCapSinglePlayer = "单人最大单位数量"
colorScheme = "配色方案"
setBackgroundImagePath = "设置背景图片路径"
backgroundTransparency = "背景透明度"
backgroundImageTransparency = "背景图片透明度"
buildings = "建筑物"
showAttackRange = "显示攻击范围"
units = "单位"
enableAnimations = "启用动画"
maxDisplayUnitGroupCount = "最大显示编队数量"
changeGameTheme = "更换游戏主题"
enhancedReinforceTroops = "增强出兵"
improvedHealthBar = "改进血量条"
showUnitTargetLine = "显示单位目标线 (多人模式受限)"
boldText = "列表粗体文字"
showExtraButton = "显示额外按钮"
renderingBackend = "渲染后端 (需要重启)"
displayUnitGroupXOffset = "编队X轴偏移"
pathfindingOptimization = "寻路优化"
mouseMoveView = "鼠标移动视角 (全屏化时)"


[extension]
extension = "扩展"
resource = "资源"
loadedInfo = "加载成功，请重启RWPP以生效"
restart = "重启"
denpendencyInfo = "该扩展依赖于以下扩展: {0}"
minGameVersion = "该扩展要求游戏版本至少为 {0}"
require = "扩展: {0} 无法被启用，请检查所需的依赖和最小游戏版本是否满足"
supportedPlatform = "支持的平台: {0}"
author = "作者: {0}"
version = "版本: {0}"

[ingame]
sendMessage = "发送消息"
sendTeamMessage = "发送团队消息"

[android]
importMod = "成功导入模组: {0}。请点击`重载`按钮更新模组列表。"
importExtension = "成功导入扩展: {0}。请点击`刷新`按钮更新扩展列表。"
importMap = "成功导入地图: {0}。"
importSave = "成功导入存档: {0}。"
importReplay = "成功导入回放: {0}。"
unknownFileTypeError = "未知文件类型: {0}"

[map.type]
SkirmishMap = "遭遇战地图"
CustomMap = "自定义地图"
SavedGame = "保存的游戏"