[mission]
title = "Missions"
type = "Mission Type"

[multiplayer]
host = "Host new game"
replay = "Watch Replay"
joinLastGame = "Join the last game"
blacklist = "blacklist"
playerLimit = "Player Limit"
enableMods = "Enable Mods"
reset = "Reset"
hostByRCN = "Host By RCN"
joinServer = "Join Server"
userName = "User Name"
useAsDefaultList = "Use as default room list"
battleroom = "Battleroom"
transferMod = "Transfer Mod (Experimental)"
addToBlackList = "Add to Blacklist"
join = "Join"
password = "password"
hostPublic = "Host Public"
hostPrivate = "Host Private"
port = "port"
admitting = """
In order to make RWPP even better, we want you to send a message to joining players to promote RWPP when you are a host
Do you agree? (The dialog will no longer be displayed, and can be changed later in Settings - Show Welcome Message)
"""

[multiplayer.filter]
filter = "Filter"
gameMapNameFilter = "Game Map Name Filter"
creatorNameFilter = "Creator Name Filter"
blacklist = "Blacklist"

[multiplayer.room]
selectMap = "Select Map"
option = "Option"
start = "Start"
changeSite = "Change Site"
addAI = "Add AI"
kick = "Kick"
apply = "Apply"
sendMessage = "Send Message"
noNukes = "No Nukes"
sharedControl = "Shared Control"
allowSpectators = "Allow Spectators"
teamLock = "Team Lock"
playerConfig = "Player Config"
startingUnit = "Starting Unit"
startingCredits = "Starting Credits"
maxPlayer = "Max Player"
incomeMultiplier = "Income Multiplier"
teamUnitCapHostedGame = "Team Unit Cap Hosted Game"
banUnits = "Ban Units"
mapView = "Map View"
mapType = "Map Type"
spawnPointTip = "The spawn point controls where on the map this player starts. Most maps use old-even spawn points."
teamTip = "Players with the same team will be allied together."

[mod]
update = "Update"
reload = "Reload"
disableAll = "DisableAll"
apply = "Apply"
cancel = "Cancel"
delete = "Delete"
enabled = "Enabled"
disabled = "Disabled"
inputFile = "Input File"
resourceBrowser = "Resource Browser"
resourceType = "Resource Type"
loadMore = "Load More"
loadInfo = "Please load file with extension '.rwmod'"
removeInfo = "The deletion of the mod has failed, please disable it and restart rwpp to try again"

[menu]
mission = "Mission"
sandbox = "Sandbox Editor"
multiplayer = "Multiplayer"
mods = "Mods"
extension = "Extension"
settings = "Settings"
exit = "Exit"
replay = "Watch Replay"

[common]
difficulty = "Difficulty"
spawnPoint = "Spawn Point"
team = "Team"
fog = "Fog"
mod = "Mod"
map = "Map"

[settings]
setExternalFolder = "Set External Folder"
manageAllFiles = "Manage All Files"
client = "Client"
theme = "Theme"
autoCheckUpdate = "Auto Check Update"
checkUpdate = "Check Update"
newVersion = "New version detected: {0}, can be downloaded from the following sites"
goToDownload = "Go to {0} to download"
prereleaseNote = "Note: this is a pre-release version"
ignoreVersion = "Ignore this version"
teamUnitCapHostedGame = "Team Unit Cap Hosted Game"
teamUnitCapSinglePlayer = "Team Unit Cap Single Player"
colorScheme = "Color Scheme"
setBackgroundImagePath = "Set Background Image Path"
backgroundTransparency = "Background Transparency"
backgroundImageTransparency = "Background Image Transparency"
buildings = "Buildings"
showAttackRange = "Show Attack Range"
units = "Units"
enableAnimations = "Enable Animations"
maxDisplayUnitGroupCount = "Max Display Unit Group Count"
changeGameTheme = "Change Game Theme"
enhancedReinforceTroops = "Enhanced Reinforce Troops"
improvedHealthBar = "Improved Health Bar"
showUnitTargetLine = "Show Unit Target Line (limited in multiplayer)"
boldText = "Bold text for list"
showExtraButton = "Show Extra Button"

[extension]
extension = "Extension"
resource = "Resource"

[ingame]
sendMessage = "Send Message"
sendTeamMessage = "Send Team Message"

[android]
importMod = "Successfully import mod: {0}. Please click `Reload` button to update the mod list."
importExtension = "Successfully import extension: {0}. Please click `Reload` button to update the extension list."
importMap = "Successfully import map: {0}."
importSave = "Successfully import save: {0}."
importReplay = "Successfully import replay: {0}."

[map.type]
SkirmishMap = "Skirmish Map"
CustomMap = "Custom Map"
SavedGame = "Saved Game"