[mission]
title = "战役"
type = "战役类型"

[multiplayer]
host = "创建房间"
replay = "观看回放"
joinLastGame = "加入上一次游戏"
blacklist = "黑名单"
playerLimit = "玩家限制"
enableMods = "启动模组"
reset = "重置"
hostByRCN = "以RCN创建房间"
joinServer = "加入服务器"
userName = "用户名"
useAsDefaultList = "用作默认房间列表"
battleroom = "战役室"
transferMod = "传输模组 (实验性)"
addToBlackList = "添加进黑名单"
join = "加入"
password = "密码"
hostPublic = "创建公开"
hostPrivate = "创建私有"
port = "端口"
admitting = """
为了使RWPP能变得更好，我们希望您在开房时向进入的玩家发送一条消息用以推广RWPP
您是否同意？(该对话框第一次显示后将不再显示，稍后可在 设置 - Show Welcome Message中更改)
"""

[multiplayer.room]
selectMap = "选择地图"
option = "选项"
start = "开始"
changeSite = "更换位置"
addAI = "添加AI"
kick = "踢出"
apply = "应用"
sendMessage = "发送消息"
noNukes = "禁用核弹"
sharedControl = "共享控制"
allowSpectators = "允许观战"
teamLock = "队伍锁定"
playerConfig = "玩家配置"
startingUnit = "初始单位"
startingCredits = "初始资金"
maxPlayer = "最大玩家数"
incomeMultiplier = "资金倍率"
teamUnitCapHostedGame = "团队最大单位数量"
banUnits = "禁用单位"
mapView = "地图视图"
mapType = "地图类型"

[mod]
update = "刷新"
reload = "重载"
disableAll = "禁用全部"
apply = "应用"
cancel = "取消"
delete = "删除"
enabled = "已启用"
disabled = "已禁用"
inputFile = "导入文件"
resourceBrowser = "资源浏览器"
resourceType = "资源类型"
loadMore = "加载更多"
loadInfo = "请导入.rwmod文件"
removeInfo = "删除模组失败，请禁用后并重启重试"

[menu]
mission = "战役"
sandbox = "沙盒编辑器"
multiplayer = "多人游戏"
mods = "模组"
extension = "扩展"
settings = "设置"
exit = "退出"
replay = "观看回放"

[common]
difficulty = "难度"
spawnPoint = "出生点"
team = "队伍"
fog = "迷雾"
mod = "模组"
map = "地图"

[settings]
setExternalFolder = "设置外部文件权限"
manageAllFiles = "设置管理所有文件"
client = "客户端"
theme = "主题"
autoCheckUpdate = "自动检测更新"
checkUpdate = "检测更新"
newVersion = "检测到新版本: {0}, 可以前往以下站点下载"
goToDownload = "前往 {0} 下载"
prereleaseNote = "注意: 该版本为预览版，可以前往爱发电下载抢先体验"
ignoreVersion = "忽略此版本"
teamUnitCapHostedGame = "团队最大单位数量"
teamUnitCapSinglePlayer = "单人最大单位数量"
colorScheme = "配色方案"
setBackgroundImagePath = "设置背景图片路径"
backgroundTransparency = "背景透明度"
backgroundImageTransparency = "背景图片透明度"
buildings = "建筑物"
showAttackRange = "显示攻击范围"
units = "单位"
enableAnimations = "启用动画"
maxDisplayUnitGroupCount = "最大显示编队数量"
changeGameTheme = "更换游戏主题"
enhancedReinforceTroops = "增强出兵"
improvedHealthBar = "改进血量条"
showUnitTargetLine = "显示单位目标线 (多人模式受限)"
boldText = "列表粗体文字"
showExtraButton = "显示额外按钮"

[extension]
extension = "扩展"
resource = "资源"


[ingame]
sendMessage = "发送消息"
sendTeamMessage = "发送团队消息"

[android]
importMod = "成功导入模组: {0}。请点击`重载`按钮更新模组列表。"
importExtension = "成功导入扩展: {0}。请点击`刷新`按钮更新扩展列表。"
importMap = "成功导入地图: {0}。"
importSave = "成功导入存档: {0}。"
importReplay = "成功导入回放: {0}。"

[map.type]
SkirmishMap = "遭遇战地图"
CustomMap = "自定义地图"
SavedGame = "保存的游戏"